apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-dcco
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-dcco
    app.kubernetes.io/part-of: integ-app-ogzd
  name: hacbs-test-project-dcco
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-dcco
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-dcco
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/nbe-e2e-fqrn-tenant/integ-app-ogzd/hacbs-test-project-dcco@sha256:69730b186677a93f396392bc34a7d3b26e336f91bcd0158f5ba98f55a979f2f6
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
